name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with: 
           java-version: '15'
      - name: Build with Gradle
        run: cd source && ./gradlew distZip
       
